apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: market-maker
resources:
  - namespace.yaml
  - configmap-symbols.yaml
  - hazelcast-members.yaml
  - postgres.yaml
  - zookeeper.yaml
  - trading-state.yaml
  - exposure-reservation.yaml
  - exchange.yaml
  - external-publisher.yaml
  - market-maker.yaml